import { LetterItem, DayItem, NumberItem, ColorItem, SeasonItem, MonthItem, OrganItem, FruitItem } from './types';

export const LETTERS: LetterItem[] = [
  { l: 'ⴰ', label: 'a', word: 'ⴰⵎⴰⵏ', emoji: '💧', img: '/src/assets/images/letters/ⴰⵎⴰⵏ.png.png', sound: '/src/assets/images/sounds/letters/ⴰ; ⴰⵎⴰⵏ.mp3.mp3' },
  { l: 'ⴱ', label: 'b', word: 'ⴰⴱⵔⵉⴷ', emoji: '🛤️', img: '/src/assets/images/letters/ⴰⴱⵔⵉⴷ.png.png', sound: '/src/assets/images/sounds/letters/ⴱ; ⴰⴱⵔⵉⴷ.mp3.mp3' },
  { l: 'ⴳ', label: 'g', word: 'ⴰⵍⵓⴳ', emoji: '📖', img: '/src/assets/images/letters/ⴰⵍⵓⴳ.png.png', sound: '/src/assets/images/sounds/letters/ⴳ; ⴰⵍⵓⴳ.mp3.mp3' },
  { l: 'ⴳⵯ', label: 'gʷ', word: 'ⴰⵣⴳⴳⵯⴰⵖ', emoji: '🎨', img: '/src/assets/images/letters/ⴰⵣⴳⴳⵯⴰⵖ.png.png', sound: '/src/assets/images/sounds/letters/ⴳⵯ; ⴰⵣⴳⴳⵯⴰⵖ (2).mp3.mp3' },
  { l: 'ⴷ', label: 'd', word: 'ⵜⴰⴷⴰⵍⴰ', emoji: '🏫', img: '/src/assets/images/letters/ⵜⴰⴷⴰⵍⴰ.png.png', sound: '/src/assets/images/sounds/letters/ⴷ; ⵜⴰⴷⴰⵍⴰ.mp3.mp3' },
  { l: 'ⴹ', label: 'ḍ', word: 'ⴰⴹⴰⵕ', emoji: '🦶', img: '/src/assets/images/letters/ⴰⴹⴰⵕ.png.png', sound: '/src/assets/images/sounds/letters/ⴹ;ⴰⴹⴰⵕ.mp3.mp3' },
  { l: 'ⴻ', label: 'e', word: 'ⵜⴰⵎⵎⴻⵎⵜ', emoji: '🍯', img: '/src/assets/images/letters/ⵜⴰⵎⵎⴻⵎⵜ.png.png', sound: '/src/assets/images/sounds/letters/ⴻ ⵜⴰⵎⵎⴻⵎⵜ.mp3.mp3' },
  { l: 'ⴼ', label: 'f', word: 'ⴰⴼⵓⵙ', emoji: '✋', img: '/src/assets/images/letters/ⴰⴼⵓⵙ.png.png', sound: '/src/assets/images/sounds/letters/ⴼ ; ⴰⴼⵓⵙ.mp3.mp3' },
  { l: 'ⴽ', label: 'k', word: 'ⵜⴰⵏⴰⴽⴰⵜ', emoji: '✏️', img: '/src/assets/images/letters/ⵜⴰⵏⴰⴽⴰⵜ.png.png', sound: '/src/assets/images/sounds/letters/ⴽ ; ⵜⴰⵏⴰⴽⴰⵜ.mp3.mp3' },
  { l: 'ⴽⵯ', label: 'kʷ', word: 'ⵉⴽⵯⵍⴰⵏ', emoji: '🎨', img: '/src/assets/images/letters/ⵉⴽⵯⵍⴰⵏ .png.png', sound: '/src/assets/images/sounds/letters/ⴽⵯ; ⵉⴽⵯⵍⴰⵏ (2).mp3.mp3' },
  { l: 'ⵀ', label: 'h', word: 'ⵜⵉⵀⵉⵔⵔⵉⵜ', emoji: '🕊️', img: '/src/assets/images/letters/ⵜⵉⵀⵉⵔⵔⵉⵜ.png.png', sound: '/src/assets/images/sounds/letters/ⵀ ; ⵜⵉⵀⵉⵔⵔⵉⵜ.mp3.mp3' },
  { l: 'ⵃ', label: 'ḥ', word: 'ⵜⴰⵃⴰⵏⵓⵜ', emoji: '🏪', img: '/src/assets/images/letters/ⵜⴰⵃⴰⵏⵓⵜ.png.png', sound: '/src/assets/images/sounds/letters/ⵃ; ⵜⴰⵃⴰⵏⵓⵜ (2).mp3.mp3' },
  { l: 'ⵄ', label: 'generic_u', word: 'ⴰⵏⵄⵏⴰⵄ', emoji: '🌿', img: '/src/assets/images/letters/ⴰⵏⵄⵏⴰⵄ.png.png', sound: '/src/assets/images/sounds/letters/ⵄ ⴰⵏⵄⵏⴰⵄ.mp3.mp3' },
  { l: 'ⵅ', label: 'x', word: 'ⴰⵅⵏⵅⴰⵍ', emoji: '💍', img: '/src/assets/images/letters/ⴰⵅⵏⵅⴰⵍ.png.png', sound: '/src/assets/images/sounds/letters/ⵅ; ⴰⵅⵏⵅⴰⵍ.mp3.mp3' },
  { l: 'ⵇ', label: 'q', word: 'ⵉⵇⵇⴰⵕⵉⴹⵏ', emoji: '💰', img: '/src/assets/images/letters/ⵉⵇⵇⴰⵕⵉⴹⵏ.png.png', sound: '/src/assets/images/sounds/letters/ⵇ; ⵉⵇⵇⴰⵕⵉⴹⵏ.mp3.mp3' },
  { l: 'ⵉ', label: 'i', word: 'ⵉⵜⵍⵉ', emoji: '🐑', img: '/src/assets/images/letters/ⵉⵜⵍⵉ.png.png', sound: '/src/assets/images/sounds/letters/ⵉ; ⵉⵜⵍⵉ (2).mp3.mp3' },
  { l: 'ⵊ', label: 'j', word: 'ⵟⵟⴰⵊⵉⵏ', emoji: '🍲', img: '/src/assets/images/letters/ⵟⵟⴰⵊⵉⵏ.png.png', sound: '/src/assets/images/sounds/letters/ⵊ; ⵟⵟⴰⵊⵉⵏ.mp3.mp3' },
  { l: 'ⵍ', label: 'l', word: 'ⵜⵉⵏⵎⴰⵍ', emoji: '🏫', img: '/src/assets/images/letters/ⵜⵉⵏⵎⴰⵍ.png.png', sound: '/src/assets/images/sounds/letters/ⵍ ; ⵜⵉⵏⵎⴰⵍ.mp3.mp3' },
  { l: 'ⵎ', label: 'm', word: 'ⵉⵎⵉ', emoji: '👄', img: '/src/assets/images/letters/ⵉⵎⵉ.png.png', sound: '/src/assets/images/sounds/letters/ⵎ; ⵉⵎⵉ.mp3.mp3' },
  { l: 'ⵏ', label: 'n', word: 'ⴰⵏⵡⴰⵍ', emoji: '🍳', img: '/src/assets/images/letters/ⴰⵏⵡⴰⵍ.png.png', sound: '/src/assets/images/sounds/letters/ⵏ ; ⴰⵏⵡⴰལ་ (2).mp3.mp3' },
  { l: 'ⵔ', label: 'r', word: 'ⵜⴰⵙⵔⵔⴰⵎⵜ', emoji: '✏️', img: '/src/assets/images/letters/ⵜⴰⵙⵔⵔⴰⵎⵜ.png.png', sound: '/src/assets/images/sounds/letters/ⵔ; ⵜⴰⵙⵔⵔⴰⵎⵜ.mp3.mp3' },
  { l: 'ⵕ', label: 'ṛ', word: 'ⵉⵥⵕⴰⵏ', emoji: '🪨', img: '/src/assets/images/letters/ⵉⵥⵕⴰⵏ.png.png', sound: '/src/assets/images/sounds/letters/ⵕ; ⵉⵥⵕⴰⵏ.mp3.mp3' },
  { l: 'ⵖ', label: 'ɣ', word: 'ⴰⵖⵕⵓⵎ', emoji: '🍞', img: '/src/assets/images/letters/ⴰⵖⵕⵓⵎ.png.png', sound: '/src/assets/images/sounds/letters/ⵖ; ⴰⵖⵕⵓⵎ (2).mp3.mp3' },
  { l: 'ⵙ', label: 's', word: 'ⵜⵓⵖⵎⴰⵙ', emoji: '🦷', img: '/src/assets/images/letters/ⵜⵓⵖⵎⴰⵙ.png.png', sound: '/src/assets/images/sounds/letters/ⵙ; ⵜⵓⵖⵎⴰⵙ.mp3.mp3' },
  { l: 'ⵚ', label: 'ṣ', word: 'ⵚⴹⵉⵚ', emoji: '6️⃣', img: '/src/assets/images/letters/ⵚⴹⵉⵚ.png.png', sound: '/src/assets/images/sounds/letters/ⵚ; ⵚⴹⵉⵚ (2).mp3.mp3' },
  { l: 'ⵛ', label: 'sh', word: 'ⵜⴰⵛⵛⴽⴰⵕⵜ', emoji: '🎒', img: '/src/assets/images/letters/ⵜⴰⵛⵛⴽⴰⵕⵜ.png.png', sound: '/src/assets/images/sounds/letters/ⵛ ⵜⴰⵛⵛⴽⴰⵕⵜ.mp3.mp3' },
  { l: 'ⵜ', label: 't', word: 'ⵜⴰⴱⴰⵏⴽⴰ', emoji: '🏦', img: '/src/assets/images/letters/ⵜⴰⴱⴰⵏⴽⴰ.png.png', sound: '/src/assets/images/sounds/letters/ⵜ ; ⵜⴰⴱⴰⵏⴽⴰ.mp3.mp3' },
  { l: 'ⵟ', label: 'ṭ', word: 'ⴱⴰⵟⴰⵟⴰ', emoji: '🥔', img: '/src/assets/images/letters/ⴱⴰⵟⴰⵟⴰ.png.png', sound: '/src/assets/images/sounds/letters/ⵟ; ⴱⴰⵟⴰⵟⴰ (2).mp3.mp3' },
  { l: 'ⵡ', label: 'w', word: 'ⵜⴰⵡⵊⴰ', emoji: '👨‍👩‍👧‍👦', img: '/src/assets/images/letters/ⵜⴰⵡⵊⴰ.png.png', sound: '/src/assets/images/sounds/letters/ⵡ; ⵜⴰⵡⵊⴰ.mp3.mp3' },
  { l: 'ⵢ', label: 'y', word: 'ⴰⵜⴰⵢ', emoji: '🍵', img: '/src/assets/images/letters/ⴰⵜⴰⵢ.png.png', sound: '/src/assets/images/sounds/letters/ⵢ; ⴰⵜⴰⵢ.mp3.mp3' },
  { l: 'ⵣ', label: 'z', word: 'ⵉⵣⵉⵎⵔ', emoji: '🐏', img: '/src/assets/images/letters/ⵉⵣⵉⵎⵔ.png.png', sound: '/src/assets/images/sounds/letters/ⵣ ; ⵉⵣⵉⵎⵔ.mp3.mp3' },
  { l: 'ⵥ', label: 'ẓ', word: 'ⴰⵏⵥⴰⵕ', emoji: '🌧️', img: '/src/assets/images/letters/ⴰⵏⵥⴰⵕ.png.png', sound: '/src/assets/images/sounds/letters/ⵥ; ⴰⵏⵥⴰⵕ.mp3.mp3' },
  { l: 'ⵓ', label: 'u', word: 'ⵓⴷⵎ', emoji: '😊', img: '/src/assets/images/letters/ⵓⴷⵎ.png.png', sound: '/src/assets/images/sounds/letters/ⵓ; ⵓⴷⵎ (2).mp3.mp3' },
];

export const DAYS: DayItem[] = [
  { tif: 'ⴰⵢⵏⴰⵙ', lat: 'Monday', icon: '🌙', color: '#4A90D9', sound: '/src/assets/images/sounds/days/ⴰⵢⵏⴰⵙ.mp3.mp3' },
  { tif: 'ⴰⵙⵉⵏⴰⵙ', lat: 'Tuesday', icon: '🔴', color: '#E74C3C', sound: '/src/assets/images/sounds/days/ⴰⵙⵉⵏⴰⵙ.mp3.mp3' },
  { tif: 'ⴰⴽⵕⴰⵙ', lat: 'Wednesday', icon: '💚', color: '#2ECC71', sound: '/src/assets/images/sounds/days/ⴰⴽⵕⴰⵙ.mp3.mp3' },
  { tif: 'ⴰⴽⵡⴰⵙ', lat: 'Thursday', icon: '⭐⭐', color: '#F5C518', sound: '/src/assets/images/sounds/days/ⴰⴽⵡⴰⵙ.mp3.mp3' },
  { tif: 'ⴰⵙⵉⵎⵡⴰⵙ', lat: 'Friday', icon: '🕌', color: '#1ABC9C', sound: '/src/assets/images/sounds/days/ⴰⵙⵉⵎⵡⴰⵙ.mp3.mp3' },
  { tif: 'ⴰⵙⵉⵚⵢⴰⵙ', lat: 'Saturday', icon: '🎉', color: '#9B59B6', sound: '/src/assets/images/sounds/days/ⴰⵙⵉⴹຍⴰⵙ.mp3.mp3' },
  { tif: 'ⴰⵙⴰⵎⴰⵙ', lat: 'Sunday', icon: '☀️', color: '#FF6B35', sound: '/src/assets/images/sounds/days/ⴰⵙⴰⵎⴰⵙ.mp3.mp3' },
];

export const NUMBERS: NumberItem[] = [
  { num: 0, tif: 'ⴰⵎⵢⴰ', emoji: '0️⃣', img: '/src/assets/images/numbers/s.png', sound: '/src/assets/images/sounds/numbers/.mp3.mp3' },
  { num: 1, tif: 'ⵢⴰⵏ', emoji: '1️⃣', img: '/src/assets/images/numbers/s (1).png.png', sound: '/src/assets/images/sounds/numbers/1.mp3.mp3' },
  { num: 2, tif: 'ⵙⵉⵏ', emoji: '2️⃣', img: '/src/assets/images/numbers/s (2).png.png', sound: '/src/assets/images/sounds/numbers/2.mp3.mp3' },
  { num: 3, tif: 'ⴽⵕⴰⴹ', emoji: '3️⃣', img: '/src/assets/images/numbers/s (3).png.png', sound: '/src/assets/images/sounds/numbers/3.mp3' },
  { num: 4, tif: 'ⴽⴽⵓⵥ', emoji: '4️⃣', img: '/src/assets/images/numbers/s (4).png.png', sound: '/src/assets/images/sounds/numbers/4.mp3.mp3' },
  { num: 5, tif: 'ⵙⵎⵎⵓⵙ', emoji: '5️⃣', img: '/src/assets/images/numbers/s (5).png.png', sound: '/src/assets/images/sounds/numbers/5.mp3.mp3' },
  { num: 6, tif: 'ⵚⴹⵉⵚ', emoji: '6️⃣', img: '/src/assets/images/numbers/s (6).png.png', sound: '/src/assets/images/sounds/numbers/6.mp3.mp3' },
  { num: 7, tif: 'ⵙⴰ', emoji: '7️⃣', img: '/src/assets/images/numbers/s (7).png.png', sound: '/src/assets/images/sounds/numbers/7.mp3.mp3' },
  { num: 8, tif: 'ⵜⴰⵎ', emoji: '8️⃣', img: '/src/assets/images/numbers/s (8).png.png', sound: '/src/assets/images/sounds/numbers/8.mp3.mp3' },
  { num: 9, tif: 'ⵜⵥⴰ', emoji: '9️⃣', img: '/src/assets/images/numbers/s (9).png.png', sound: '/src/assets/images/sounds/numbers/9.mp3.mp3' },
  { num: 10, tif: 'ⵎⵔⴰⵡ', emoji: '🔟', img: '/src/assets/images/numbers/s (10).png.png', sound: '/src/assets/images/sounds/numbers/10.mp3.mp3' },
  { num: 11, tif: 'ⵢⴰⵏ ⴷ ⵎⵔⴰⵡ', emoji: '1️⃣1️⃣', img: '/src/assets/images/numbers/s (11).png.png', sound: '/src/assets/images/sounds/numbers/11.mp3.mp3' },
  { num: 12, tif: 'ⵙⵉⵏ ⴷ ⵎⵔⴰⵡ', emoji: '1️⃣2️⃣', img: '/src/assets/images/numbers/s (12).png.png', sound: '/src/assets/images/sounds/numbers/12.mp3.mp3' },
  { num: 13, tif: 'ⴽⵕⴰⴹ ⴷ ⵎⵔⴰⵡ', emoji: '1️⃣3️⃣', img: '/src/assets/images/numbers/s (13).png.png', sound: '/src/assets/images/sounds/numbers/13.mp3.mp3' },
  { num: 14, tif: 'ⴽⴽⵓⵥ ⴷ ⵎⵔⴰⵡ', emoji: '1️⃣4️⃣', img: '/src/assets/images/numbers/s (14).png.png', sound: '/src/assets/images/sounds/numbers/14.mp3.mp3' },
  { num: 15, tif: 'ⵙⵎⵎⵓⵙ ⴷ ⵎⵔⴰⵡ', emoji: '1️⃣5️⃣', img: '/src/assets/images/numbers/s (15).png.png', sound: '/src/assets/images/sounds/numbers/15.mp3.mp3' },
  { num: 16, tif: 'ⵚⴹⵉⵚ ⴷ ⵎⵔⴰⵡ', emoji: '1️⃣6️⃣', img: '/src/assets/images/numbers/s (16).png.png', sound: '/src/assets/images/sounds/numbers/16.mp3.mp3' },
  { num: 17, tif: 'ⵙⴰ ⴷ ⵎⵔⴰⵡ', emoji: '1️⃣7️⃣', img: '/src/assets/images/numbers/s (17).png.png', sound: '/src/assets/images/sounds/numbers/17.mp3.mp3' },
  { num: 18, tif: 'ⵜⴰⵎ ⴷ ⵎⵔⴰⵡ', emoji: '1️⃣8️⃣', img: '/src/assets/images/numbers/s (18).png.png', sound: '/src/assets/images/sounds/numbers/18.mp3.mp3' },
  { num: 19, tif: 'ⵜⵥⴰ ⴷ ⵎⵔⴰⵡ', emoji: '1️⃣9️⃣', img: '/src/assets/images/numbers/s (19).png.png', sound: '/src/assets/images/sounds/numbers/19.mp3.mp3' },
  { num: 20, tif: 'ⴰଗⵏⴰⵔ', emoji: '2️⃣0️⃣', img: '/src/assets/images/numbers/s (20).png.png', sound: '/src/assets/images/sounds/numbers/20.mp3.mp3' },
];

export const COLORS: ColorItem[] = [
  { tif: 'ⵓⵎⵍⵉⵍ', lat: 'White', bg: '#FFFFFF', text: '#333333', sound: '/src/assets/images/sounds/color/ⵓⵎⵍⵉⵍ.mp3' },
  { tif: 'ⴰⵡⵔⴰⵖ', lat: 'Yellow', bg: '#F5C518', text: '#5A3E00', sound: '/src/assets/images/sounds/color/ⴰⵡⵔⴰⵖ.mp3' },
  { tif: 'ⴰⵏⵉⵍⵉ', lat: 'Blue', bg: '#1565C0', text: '#E3F2FD', sound: '/src/assets/images/sounds/color/ⴰⵏⵉⵍⵉ.mp3' },
  { tif: 'ⴰⵊⵏⵊⴰⵕⵉ', lat: 'Purple', bg: '#6A1B9A', text: '#F3E5F5', sound: '/src/assets/images/sounds/color/ⴰⵊⵏⵊⴰⵕⵉ.mp3' },
  { tif: 'ⴰⵍⵜⵛⵉⵏⵉ', lat: 'Orange', bg: '#E65100', text: '#FFF3E0', sound: '/src/assets/images/sounds/color/ⴰⵍⵜⵛⵉⵏⵉ.mp3' },
  { tif: 'ⴰⵣⴳⴳⵯⴰⵖ', lat: 'Red', bg: '#B71C1C', text: '#FFEBEE', sound: '/src/assets/images/sounds/color/ⴰⵣⴳⴳⵯⴰⵖ.mp3' },
  { tif: 'ⴰⵣⴳⵣⴰⵡ', lat: 'Green', bg: '#1B5E20', text: '#E8F5E9', sound: '/src/assets/images/sounds/color/ⴰⵣⴳⵣⴰⵡ.mp3' },
  { tif: 'ⴰⴱⵔⴽⴰⵏ', lat: 'Black', bg: '#212121', text: '#F5F5F5', sound: '/src/assets/images/sounds/color/ⴰⴱⵔⴽⴰⵏ.mp3' },
  { tif: 'ⴰⴷⵎⵎⴰⵏ', lat: 'Brown', bg: '#4E342E', text: '#EFEBE9', sound: '/src/assets/images/sounds/color/ⴰⴷⵎⵎⴰⵏ.mp3' },
];

export const SEASONS: SeasonItem[] = [
  { tif: 'ⵜⴰⴼⵙⵓⵜ', lat: 'Spring', bg: 'linear-gradient(135deg,#2ECC71,#1A9950)', emoji: '🌸', months: 'ⵎⴰⵕⵚ · ⵉⴱⵔⵉⵔ · ⵎⴰⵢⵢⵓ', img: '/src/assets/images/spring_season_1779576383086.png', sound: '/src/assets/images/sounds/season/ⵜⴰⴼⵙⵓⵜ.mp3.mp3' },
  { tif: 'ⴰⵏⴱⴷⵓ', lat: 'Summer', bg: 'linear-gradient(135deg,#FF6B35,#C0392B)', emoji: '☀️', months: 'ⵢⵓⵏⵢⵓ · ⵢⵓⵍⵢⵓⵣ · ⵖⵓⵛⵜ', img: '/src/assets/images/summer_season_1779576398217.png', sound: '/src/assets/images/sounds/season/ⴰⵏⴱⴷⵓ.mp3.mp3' },
  { tif: 'ⴰⵎⵡⴰⵏ', lat: 'Autumn', bg: 'linear-gradient(135deg,#E67E22,#A04000)', emoji: '🍂', months: 'ⵛⵓⵜⴰⵏⴱⵉⵔ · ⴽⵜⵓⴱⵕ · ⵏⵓⵡⴰⵏⴱⵉⵔ', img: '/src/assets/images/autumn_season_1779576412053.png', sound: '/src/assets/images/sounds/season/ⴰⵎⵡⴰⵏ.mp3.mp3' },
  { tif: 'ⵜⴰﮕⵔⵙⵜ', lat: 'Winter', bg: 'linear-gradient(135deg,#3498DB,#1A5276)', emoji: '❄️', months: 'ⴷⵓⵊⴰⵏⴱⵉⵔ · ⵉⵏⵏⴰⵢⵔ · ⴱⵕⴰⵢⵕ', img: '/src/assets/images/winter_season_1779576428951.png', sound: '/src/assets/images/sounds/season/ⵜⴰﮕⵔⵙⵜ.mp3.mp3' },
];

export const MONTHS: MonthItem[] = [
  { num: 1, tif: 'ⵉⵏⵏⴰⵢⵔ', emoji: '❄️', bg: '#1A5276', sound: '/src/assets/images/sounds/season/ⵉⵏⵏⴰⵢⵔ.mp3.mp3' },
  { num: 2, tif: 'ⴱⵕⴰⵢⵕ', emoji: '🌨️', bg: '#1565C0', sound: '/src/assets/images/sounds/season/ⴱⵕⴰⵢⵕ.mp3.mp3' },
  { num: 3, tif: 'ⵎⴰⵕⵚ', emoji: '🌱', bg: '#1B5E20', sound: '/src/assets/images/sounds/season/ⵎⴰⵕⵚ.mp3.mp3' },
  { num: 4, tif: 'ⵉⴱⵔⵉⵔ', emoji: '🌸', bg: '#2E7D32', sound: '/src/assets/images/sounds/season/ⵉⴱⵔⵉⵔ.mp3.mp3' },
  { num: 5, tif: 'ⵎⴰⵢⵢⵓ', emoji: '🌿', bg: '#388E3C', sound: '/src/assets/images/sounds/season/ⵎⴰⵢⵢⵓ.mp3.mp3' },
  { num: 6, tif: 'ⵢⵓⵏⵢⵓ', emoji: '☀️', bg: '#E65100', sound: '/src/assets/images/sounds/season/ⵢⵓⵏⵢⵓ.mp3.mp3' },
  { num: 7, tif: 'ⵢⵓⵍⵢⵓⵣ', emoji: '🏖️', bg: '#BF360C', sound: '/src/assets/images/sounds/season/ⵢⵓⵍⵢⵓⵡ.mp3.mp3' },
  { num: 8, tif: 'ⵖⵓⵛⵜ', emoji: '🌅', bg: '#C62828', sound: '/src/assets/images/sounds/season/ⵖⵓⵛⵜ.mp3.mp3.aac' },
  { num: 9, tif: 'ⵛⵓⵜⴰⵏⴱⵉⵔ', emoji: '🍂', bg: '#E67E22', sound: '/src/assets/images/sounds/season/ⵛⵓⵜⴰⵏⴱⵉⵔ.mp3.mp3' },
  { num: 10, tif: 'ⴽⵜⵓⴱⵕ', emoji: '🍁', bg: '#A04000', sound: '/src/assets/images/sounds/season/ⴽⵜⵓⴱⵕ.mp3.mp3' },
  { num: 11, tif: 'ⵏⵓⵡⴰⵏⴱⵉⵔ', emoji: '🌧️', bg: '#5D4037', sound: '/src/assets/images/sounds/season/ⵏⵓⵡⴰⵏⴱⵉⵔ.mp3.mp3' },
  { num: 12, tif: 'ⴷⵓⵊⴰⵏⴱⵉⵔ', emoji: '⛄', bg: '#0D47A1', sound: '/src/assets/images/sounds/season/ⴷⵓⵊⴰⵏⴱⵉⵔ.mp3.mp3' },
];

export const ORGANS: OrganItem[] = [
  { tif: 'ⵉⵅⴼ', lat: 'Hair/Head', emoji: '🧑', img: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=400&q=80', sound: '/src/assets/images/sounds/organs/ⵉⵅⴼ.mp3.mp3' },
  { tif: 'ⴰⵎⵣⵣⵓⵖ', lat: 'Head', emoji: '👤', img: 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=400&q=80', sound: '/src/assets/images/sounds/organs/ⴰⵎⵣⵣⵓⵖ.mp3.mp3' },
  { tif: 'ⵜⵉⵟⵟ', lat: 'Eye', emoji: '👁️', img: 'https://images.unsplash.com/photo-1544717297-fa95b6ee9643?auto=format&fit=crop&w=400&q=80', sound: '/src/assets/images/sounds/organs/ⵜⵉⵟⵟ.mp3.mp3' },
  { tif: 'ⴰⵎⵣⵣⵓⵖ_ear', lat: 'Ear', emoji: '👂', img: 'https://images.unsplash.com/photo-1516259762381-22954d7d3ad2?auto=format&fit=crop&w=400&q=80', sound: '/src/assets/images/sounds/organs/ⴰⵎⵣⵣⵓⵖ.mp3.mp3' },
  { tif: 'ⵜⵉⵏⵣⴰⵔ', lat: 'Nose', emoji: '👃', img: 'https://images.unsplash.com/photo-1512438248247-f0f2a5a8b7f0?auto=format&fit=crop&w=400&q=80', sound: '/src/assets/images/sounds/organs/ⵜⵉⵏⵣⴰⵔ.mp3.mp3' },
  { tif: 'ⵉⵎⵉ', lat: 'Mouth', emoji: '👄', img: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=400&q=80', sound: '/src/assets/images/sounds/organs/ⵉⵎⵉ.mp3.mp3' },
  { tif: 'ⵜⵓⵖﻤⴰⵙ', lat: 'Teeth', emoji: '🦷', img: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?auto=format&fit=crop&w=400&q=80', sound: '/src/assets/images/sounds/organs/ⵜⵓⵖﻤⴰⵙ.mp3.mp3' },
  { tif: 'ⴰⴼⵓⵙ', lat: 'Hand', emoji: '✋', img: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=400&q=80', sound: '/src/assets/images/sounds/organs/ⴰⴼⵓⵙ.mp3.mp3' },
  { tif: 'ⴰⴹⴰⴹ', lat: 'Fingers', emoji: '💅', img: 'https://images.unsplash.com/photo-1481887328591-3e277f9473dc?auto=format&fit=crop&w=400&q=80', sound: '/src/assets/images/sounds/organs/ⴰⴹⴰⴹ.mp3.mp3' },
  { tif: 'ⴰⴼⵓⴷ', lat: 'Knee', emoji: '🦵', img: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&w=400&q=80', sound: '/src/assets/images/sounds/organs/ⴰⴼⵓⴷ.mp3.mp3' },
  { tif: 'ⴰⴹⴰⵕ', lat: 'Foot', emoji: '🦶', img: 'https://images.unsplash.com/photo-1519689680058-324335c77eba?auto=format&fit=crop&w=400&q=80', sound: '/src/assets/images/sounds/organs/ⴰⴹⴰⵕ.mp3.mp3' },
];

export const FRUITS: FruitItem[] = [
  { tif: 'ⵅⵉⵣⵣⵓ', lat: 'Carrot', emoji: '🥕', img: '/src/assets/images/fruits/ⵅⵉⵣⵣⵓ.png.png', sound: '/src/assets/images/sounds/fruits/ⵅⵉⵣⵣⵓ.mp3.mp3' },
  { tif: 'ⵎⴰⵟⵉⵛⴰ', lat: 'Tomato', emoji: '🍅', img: '/src/assets/images/fruits/ⵎⴰⵟⵉⵛⴰ.png.png', sound: '/src/assets/images/sounds/fruits/ⵎⴰⵟⵉⵛⴰ.mp3.mp3' },
  { tif: 'ⴰⵥⴰⵍⵉⵎ', lat: 'Watermelon', emoji: '🍉', img: '/src/assets/images/fruits/ⴰⵥⴰⵍⵉⵎ.png.png', sound: '/src/assets/images/sounds/fruits/ⴰⵥⴰⵍⵉⵎ.mp3.mp3' },
  { tif: 'ⴰⴽⵯⴼⴰⵢ', lat: 'Potato', emoji: '🥔', img: '/src/assets/images/fruits/ⴰⴽⵯⴼⴰⵢ.png.png', sound: '/src/assets/images/sounds/fruits/ⴰⴽⵯⴼⴰⵢ.mp3.mp3' },
  { tif: 'ⴰⴷⴼⴼⵓ', lat: 'Apple', emoji: '🍎', img: '/src/assets/images/fruits/ⴰⴷⴼⴼⵓ.png.png', sound: '/src/assets/images/sounds/fruits/ⴰⴷⴼⴼⵓ.mp3.mp3' },
  { tif: 'ⴰⵎⵎⴰⵣ', lat: 'Cherry', emoji: '🍒', img: '/src/assets/images/fruits/ⴰⵎⵎⴰⵣ.png.png', sound: '/src/assets/images/sounds/fruits/ⴰⵎⵎⴰⵣ.mp3.mp3' },
  { tif: 'ⴰⵖⵔⴰⴳⴳⴰⵏ', lat: 'Pomegranate', emoji: '🍈', img: '/src/assets/images/fruits/ⴰⵖⵔⴰⴳⴳⴰⵏ.png.png', sound: '/src/assets/images/sounds/fruits/ⴰⵖⵔⴰⴳⴳⴰⵏ.mp3.mp3' },
  { tif: 'ⴰⵣⴰⵜⵉⵎ', lat: 'Olives', emoji: '🫒', img: '/src/assets/images/fruits/ⴰⵣⴰⵜⵉⵎ.png.png', sound: '/src/assets/images/sounds/fruits/ⴰⵣⴰⵜⵉⵎ.mp3.mp3' },
  { tif: 'ⵜⵉⵣⵡⵍⵜ', lat: 'Dates', emoji: '🌴', img: '/src/assets/images/fruits/ⵜⵉⵣⵡⵍⵜ.png.png', sound: '/src/assets/images/sounds/fruits/ⵜⵉⵣⵡⵍⵜ.mp3.mp3' },
  { tif: 'ⴰⴹⵉⵍ', lat: 'Grapes', emoji: '🍇', img: '/src/assets/images/fruits/ⴰⴹⵉⵍ.png.png', sound: '/src/assets/images/sounds/fruits/ⴰⴹⵉⵍ.mp3.mp3' },
  { tif: 'ⴰଗⴰⵏ', lat: 'Cucumber', emoji: '🥒', img: 'https://images.unsplash.com/photo-1449339044510-acdb62580a8c?auto=format&fit=crop&w=400&q=80', sound: '/src/assets/images/sounds/fruits/ⴰଗⴰⵏ.mp3.mp3' },
  { tif: 'ⵜⵉⴳⵍⴰⵢ', lat: 'Garlic', emoji: '🧄', img: '/src/assets/images/fruits/ⵜⵉⴳⵍⴰⵢ.png.png', sound: '/src/assets/images/sounds/fruits/ⵜⵉⴳⵍⴰⵢ.mp3.mp3' },
  { tif: 'ⴰⵣⵄⵍⵓⴽ', lat: 'Eggplant', emoji: '🍆', img: '/src/assets/images/fruits/ⴰⵣⵄⵍⵓⴽ.png.png', sound: '/src/assets/images/sounds/fruits/ⴰⵣⵄⵍوك.mp3.mp3' },
  { tif: 'ⵜⴰⵍⵍⵓⵖⴷⴰ', lat: 'Onion', emoji: '🧅', img: '/src/assets/images/fruits/ⵜⴰⵍⵍⵓⵖⴷⴰ.png.png', sound: '/src/assets/images/sounds/fruits/ⵜⴰⵍⵍⵓⵖⴷⴰ.mp3.mp3' },
  { tif: 'ⵜⴰⵎⵓⴷⵉⵜ', lat: 'Figs', emoji: '🍇', img: '/src/assets/images/fruits/ⵜⴰⵎⵓⴷⵉⵜ.png.png', sound: '/src/assets/images/sounds/fruits/ⵜⴰⵎⵓⴷⵉⵜ.mp3.mp3' },
  { tif: 'ⴰⴼⵉⵔⴰⵙ', lat: 'Pear', emoji: '🍐', img: '/src/assets/images/fruits/ⴰⴼⵉⵔⴰⵙ.png.png', sound: '/src/assets/images/sounds/fruits/ⴰⴼⵉⵔⴰⵙ.mp3.mp3' },
  { tif: 'ⵜⵉⵔⴽⵎⵉⵏ', lat: 'Turnip', emoji: '🥬', img: '/src/assets/images/fruits/ⵜⵉⵔⴽⵎⵉⵏ.png.png', sound: '/src/assets/images/sounds/fruits/ⵜⵉⵔⴽⵎⵉⵏ.mp3.mp3' },
  { tif: 'ⵍⵉⵜⵛⵉⵏ', lat: 'Orange', emoji: '🍊', img: '/src/assets/images/fruits/ⵍⵉⵜⵛⵉⵏ.png.png', sound: '/src/assets/images/sounds/fruits/ⵍⵉⵜⵛⵉⵏ.mp3.mp3' },
  { tif: 'ⵜⵉⴽⵍⵉⵍⵜ', lat: 'Artichoke', emoji: '🌿', img: '/src/assets/images/fruits/ⵜⵉⴽⵍⵉⵍⵜ.png.png', sound: '/src/assets/images/sounds/fruits/ⵜⵉⴽⵍⵉⵍⵜ.mp3.mp3' },
];

export const GRADS = [
  ['linear-gradient(135deg, #FF6B35, #E04010)', '#A03010'],
  ['linear-gradient(135deg, #4A90D9, #1A5FAB)', '#0A3F7A'],
  ['linear-gradient(135deg, #F5C518, #D4A00A)', '#9A7500'],
  ['linear-gradient(135deg, #2ECC71, #1A9950)', '#0E6030'],
  ['linear-gradient(135deg, #9B59B6, #6C3483)', '#4A1A6A'],
  ['linear-gradient(135deg, #E74C8B, #B0245E)', '#7A0A3A'],
  ['linear-gradient(135deg, #1ABC9C, #0E8A72)', '#085A48'],
  ['linear-gradient(135deg, #E67E22, #B85A00)', '#7A3800'],
  ['linear-gradient(135deg, #3498DB, #1A6FA8)', '#0A4A72'],
  ['linear-gradient(135deg, #27AE60, #145A32)', '#0A3A1E'],
  ['linear-gradient(135deg, #8E44AD, #5B2C6F)', '#3A1050'],
  ['linear-gradient(135deg, #E74C3C, #A93226)', '#6A1E16'],
];
